### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by facastagnini**
Hi @Padgett!

I had some time to add linting to the project. I also added a couple badges and my name to the README as a contributor.

You can see the type of tests done here: https://travis-ci.org/facastagnini/chef-raspberry-pi

I hope it helps!
Federico

### CODE REVIEW

**Comment by facastagnini** [comment]
Of course there is more to be done, but this is a good first step.

**Comment by Padgett** [comment]
This looks awesome! Give me a bit of time to review and we should be able to merge this in!

Thanks!

**Comment by facastagnini** [comment]
You will have to enable the testing on travis and gemmasium, they are both free.

**Comment by Padgett** [comment]
Alright, think I got that setup correctly. This looks great, thank you!

**Pull request merged**
